version: '3'
services:

  web:
    build: web
    environment:
      VIRTUAL_HOST: ${DEFAULT_HOST:-localhost}
      CERT_NAME: default
    depends_on:
      - generator
    volumes:
      - pub:/usr/share/nginx/html:ro

  generator:
    build: generator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - pub:/app/pub:delegated

volumes:
  pub:

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
